"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins
import collections.abc
import flwr.proto.node_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EVENT_TYPE_UNSPECIFIED: _EventType.ValueType  # 0
    EVENT_TYPE_ROUND_STARTED: _EventType.ValueType  # 1
    """Round lifecycle events"""
    EVENT_TYPE_ROUND_CONFIGURE_SENT: _EventType.ValueType  # 2
    EVENT_TYPE_ROUND_FIT_RECEIVED: _EventType.ValueType  # 3
    EVENT_TYPE_ROUND_FIT_AGGREGATED: _EventType.ValueType  # 4
    EVENT_TYPE_ROUND_EVALUATE_RECEIVED: _EventType.ValueType  # 5
    EVENT_TYPE_ROUND_EVALUATE_AGGREGATED: _EventType.ValueType  # 6
    EVENT_TYPE_ROUND_COMPLETED: _EventType.ValueType  # 7
    EVENT_TYPE_ROUND_FAILED: _EventType.ValueType  # 8
    EVENT_TYPE_RUN_STARTED: _EventType.ValueType  # 9
    """Run lifecycle events"""
    EVENT_TYPE_RUN_COMPLETED: _EventType.ValueType  # 10
    EVENT_TYPE_RUN_FAILED: _EventType.ValueType  # 11
    EVENT_TYPE_NODE_FIT_STARTED: _EventType.ValueType  # 12
    """Node fit events"""
    EVENT_TYPE_NODE_FIT_COMPLETED: _EventType.ValueType  # 13
    EVENT_TYPE_NODE_FIT_FAILED: _EventType.ValueType  # 14
    EVENT_TYPE_NODE_EVALUATE_STARTED: _EventType.ValueType  # 15
    """Node evaluate events"""
    EVENT_TYPE_NODE_EVALUATE_COMPLETED: _EventType.ValueType  # 16
    EVENT_TYPE_NODE_EVALUATE_FAILED: _EventType.ValueType  # 17
    EVENT_TYPE_NODE_TRAINING_PROGRESS: _EventType.ValueType  # 18
    """Node progress events"""

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

EVENT_TYPE_UNSPECIFIED: EventType.ValueType  # 0
EVENT_TYPE_ROUND_STARTED: EventType.ValueType  # 1
"""Round lifecycle events"""
EVENT_TYPE_ROUND_CONFIGURE_SENT: EventType.ValueType  # 2
EVENT_TYPE_ROUND_FIT_RECEIVED: EventType.ValueType  # 3
EVENT_TYPE_ROUND_FIT_AGGREGATED: EventType.ValueType  # 4
EVENT_TYPE_ROUND_EVALUATE_RECEIVED: EventType.ValueType  # 5
EVENT_TYPE_ROUND_EVALUATE_AGGREGATED: EventType.ValueType  # 6
EVENT_TYPE_ROUND_COMPLETED: EventType.ValueType  # 7
EVENT_TYPE_ROUND_FAILED: EventType.ValueType  # 8
EVENT_TYPE_RUN_STARTED: EventType.ValueType  # 9
"""Run lifecycle events"""
EVENT_TYPE_RUN_COMPLETED: EventType.ValueType  # 10
EVENT_TYPE_RUN_FAILED: EventType.ValueType  # 11
EVENT_TYPE_NODE_FIT_STARTED: EventType.ValueType  # 12
"""Node fit events"""
EVENT_TYPE_NODE_FIT_COMPLETED: EventType.ValueType  # 13
EVENT_TYPE_NODE_FIT_FAILED: EventType.ValueType  # 14
EVENT_TYPE_NODE_EVALUATE_STARTED: EventType.ValueType  # 15
"""Node evaluate events"""
EVENT_TYPE_NODE_EVALUATE_COMPLETED: EventType.ValueType  # 16
EVENT_TYPE_NODE_EVALUATE_FAILED: EventType.ValueType  # 17
EVENT_TYPE_NODE_TRAINING_PROGRESS: EventType.ValueType  # 18
"""Node progress events"""
global___EventType = EventType

@typing.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TIMESTAMP_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    run_id: builtins.int
    node_id: builtins.int
    event_type: global___EventType.ValueType
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        timestamp: builtins.float = ...,
        run_id: builtins.int = ...,
        node_id: builtins.int = ...,
        event_type: global___EventType.ValueType = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["event_type", b"event_type", "metadata", b"metadata", "node_id", b"node_id", "run_id", b"run_id", "timestamp", b"timestamp"]) -> None: ...

global___Event = Event

@typing.final
class PushEventsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    run_id: builtins.int
    @property
    def node(self) -> flwr.proto.node_pb2.Node: ...
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Event]: ...
    def __init__(
        self,
        *,
        node: flwr.proto.node_pb2.Node | None = ...,
        run_id: builtins.int = ...,
        events: collections.abc.Iterable[global___Event] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["node", b"node"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["events", b"events", "node", b"node", "run_id", b"run_id"]) -> None: ...

global___PushEventsRequest = PushEventsRequest

@typing.final
class PushEventsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PushEventsResponse = PushEventsResponse
